# 명령어 상수
CMD_PREFIX = "$CMD"
TERMINATOR = "\r\n"

# 시스템 분류 상수
AIR_SYSTEM = "AIR"
DSCT_SYSTEM = "DSCT"

# 버튼 상태 관련 상수
ON_STATE = "ON"
OFF_STATE = "OFF"
OPEN_STATE = "OPEN"
CLOSE_STATE = "CLOSE"

# AIRCON 명령어 상수
FAN_CMD = "FAN"
CON_F_CMD = "CON_F"
FSPD_CMD = "FSPD"
CON_SPD_CMD = "CON_SPD"
ALTDMP_CMD = "ALTDMP"
ALBDMP_CMD = "ALBDMP"
ARTDMP_CMD = "ARTDMP"
ARBDMP_CMD = "ARBDMP"
INVERTER_CMD = "INVERTER"
CLUCH_CMD = "CLUCH"

# DESICCANT 명령어 상수
FAN1_CMD = "FAN1"
FAN2_CMD = "FAN2"
FAN3_CMD = "FAN3"
FAN4_CMD = "FAN4"
SPD_CMD = "SPD"
DSCT_FAN_CMD = "FAN"
LDMP_CMD = "LDMP"
RDMP_CMD = "RDMP"
LHOT_CMD = "LHOT"
LCOOL_CMD = "LCOOL"
RHOT_CMD = "RHOT"
RCOOL_CMD = "RCOOL"

# DAMPER 명령어 상수
DMP1_OPEN_CMD = "DMP1,OPEN"
DMP1_CLOSE_CMD = "DMP1,CLOSE"
DMP2_OPEN_CMD = "DMP2,OPEN"
DMP2_CLOSE_CMD = "DMP2,CLOSE"
DMP3_OPEN_CMD = "DMP3,OPEN"
DMP3_CLOSE_CMD = "DMP3,CLOSE"
DMP4_OPEN_CMD = "DMP4,OPEN"
DMP4_CLOSE_CMD = "DMP4,CLOSE"

# PUMPER & SOL 명령어 상수
PUMP1_CMD = "PUMP1"
PUMP2_CMD = "PUMP2"
SOL1_CMD = "SOL1"
SOL2_CMD = "SOL2"
SOL3_CMD = "SOL3"
SOL4_CMD = "SOL4"

# AUTO 모드 명령어 상수
AUTO_CMD = "AUTO"
TEMP_CMD = "TEMP"

# 스타일 관련 상수
BUTTON_ON_STYLE = "background-color: rgb(43, 179, 43); color: rgb(255,255,255);"
BUTTON_OFF_STYLE = "background-color: rgb(186,186,186); color: rgb(0,0,0);"

# 추가 버튼 스타일 상수
BUTTON_DEFAULT_STYLE = "font-size: 14px; background-color: rgb(186,186,186); color: rgb(0,0,0);"
BUTTON_SPEED_STYLE = "background-color: rgb(186,186,186); font-size: 14px;"
BUTTON_PUMP_STYLE = "background-color: rgb(186,186,186); color: rgb(0,0,0);"

# COMPRESSOR 버튼 기준 표준 스타일 (AIRCON CONTROLS의 COMPRESSOR 버튼과 동일)
BUTTON_STANDARD_STYLE = "font-size: 14px; font-weight: bold;"

# 기본 설정값
DEFAULT_BAUDRATE = 115200

